### ISSUE TITLE
how data generation at release works now?

### ISSUE THREAD

**Issue by eparejatobes** [era7bio/db.rna16S#46] opened 2016-08-10 10:21 UTC
@laughedelic I'm not following ohnosequences/nice-sbt-settings/49 in full detail, could you tell how we will be running data generation? I also assume that we will need to update/change something here about it?

**Comment by laughedelic** [comment] 2016-08-10 10:49
The idea is to use release-only tests to launch instances with given bundles that generate data. The problem is that for that one needs to publish first a fat-jar, that includes test sources, but we don't have scoped `test:publish` or `releaseTest:publish`, so I what I'm doing now in https://github.com/ohnosequences/nice-sbt-settings/pull/49 is to include test sources in the fat-jar manually (and only there), while it will be published together witht the other artifacts (in `*:publish`)

**Comment by eparejatobes** [comment] 2016-08-10 13:07
OK. What about running mg7?

**Comment by laughedelic** [comment] 2016-08-10 13:17
Mm.. I don't know. We don't have a ready to use way to automise it (again, it's about chaining loquats https://github.com/ohnosequences/loquat/issues/33).

**Comment by laughedelic** [comment] 2016-08-13 00:54
I think that for now this could be left manual:
1. make release the usual way
2. being on that version tag, do all the steps from the docs for generating data

**Comment by laughedelic** [comment] 2016-08-18 22:51
Closing this. Should be discussed somewhere else. Here we have #34 for whatever will be done.

**Closed as completed by laughedelic** 2016-08-18 22:51 UTC
Labels: question
